[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fuul_solana = "DiMe3wTNXQcJv8i2chyiwJcjtGcy6zooVsgig9cfihSg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/admin.json"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899
slots_per_epoch = "32"
