name: Fuul test CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Anchor
        uses: ./.github/actions/setup-anchor
        with:
          anchor-version: '0.32.1'
          solana-cli-version: '2.3.13'
          node-version: '23.11.1'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build:all

      - name: Run Tests
        run: yarn test:all
